Chapter_4/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.homepage, name='home'),
    path('about/', views.aboutpage, name='about'),
    path('posts/', include('posts.urls'))
]

Chapter_4/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.postlistpage, name='list'),
    path('<slug:slug>', views.singlepost, name='post')
]

Chapter_4/posts/models.py
from django.db import models

# Create your models here.
class Posts(models.Model):
    username = models.CharField(max_length=20)
    title = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=20)
    text = models.TextField(max_length=100)

    def __str__(self):
        return f"{self.date.year}: {self.username}"

Chapter_4/myproject/views.py
from django.shortcuts import render

def homepage(req):
    return render(req, 'pages/home.html')

def aboutpage(req):
    return render(req, 'pages/about.html')

Chapter_4/posts/views.py
from django.shortcuts import render
from .models import Posts

posts = Posts.objects

# Create your views here.
def postlistpage(req):
    return render(req, 'posts.html', {'posts': posts.all().order_by('-date')})

def singlepost(req, slug):
    return render(req, 'single_post.html', {'post': posts.get(slug=slug)})

Chapter_4/posts/templates/posts.html
{% extends 'layout.html' %}

{% block title %}
    Posts
{% endblock %}

{% block content %}
    <div class="posts">
        {% for post in posts %}
            <div class="post" style="border: 2px solid white; margin: 5px 0; padding: 10px;">
                <h1><a href="{% url 'posts:post' slug=post.slug %}">{{ post.title }}</a></h1>
                <h3 style="text-align: start;">by: {{ post.username }}</h3>
                <h6 style="text-align: start;">on: {{ post.date }}</h6> <hr/>
                <p style="margin-top: 5px;">{{ post.text }}</p>
            </div>
        {% endfor %}
    </div>
    
{% endblock %}

Chapter_4/posts/templates/single_post.html
{% extends 'layout.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <h1><a href="">{{ post.title }}</a></h1>
    <h3 style="text-align: start;">by: {{ post.username }}</h3>
    <h6 style="text-align: start;">on: {{ post.date }}</h6> <hr/>
    <p style="margin-top: 5px;">{{ post.text }}</p>
    <br>
    <a href="{% url 'posts:list' %}" style="text-align: end;">Go back</a>
{% endblock %}

Chapter_4/templates/pages/about.html
{% extends 'layout.html' %}

{% block title %}
    About
{% endblock %}

{% block content %}
    <h1>About Us</h1>
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ut ipsam odio blanditiis quia, esse aliquid delectus sed eos quo omnis molestias rem officiis quaerat fugit mollitia, veritatis nam laboriosam modi.</p>
{% endblock %}

Chapter_4/templates/pages/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home Pgae</h1>
    <p>This is homepage</p>
{% endblock %}