Chapter_5/datas/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts_page, name='list'),
    path('<slug:slug>', views.sigle_post, name='single')
]

Chapter_5/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('posts/', include('datas.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Chapter_5/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('resgister/', views.registerpage, name='register')
]

Chapter_5/datas/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.
class BlogPosts(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField(max_length=150)
    image = models.ImageField(blank=True, default='qr.png')
    slug = models.SlugField(blank= True, unique=True)
    username = models.CharField(max_length=20)
    date = models.DateTimeField(auto_now_add=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.date.year}-{self.title}'

Chapter_5/users/models.py
from django.db import models

# Create your models here.

Chapter_5/datas/views.py
from django.shortcuts import render
from .models import BlogPosts

blogpost = BlogPosts.objects

# Create your views here.
def posts_page(req):
    return render(req, 'posts.html', {'posts': blogpost.all()})

def sigle_post(req, slug):
    return render(req, 'single_post.html', {'post': blogpost.get(slug=slug)})

Chapter_5/project/views.py
from django.shortcuts import render

def homepage(req):
    return render(req, 'pages/home.html')

Chapter_5/users/views.py
from django.shortcuts import render

# Create your views here.
def registerpage(req):
    return render(req, 'register.html')

Chapter_5/datas/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    {% for post in posts %}
        <h1><a href="{% url 'posts:single' slug=post.slug %}">
            {{ post.title }}
        </a></h1>
        <div class="info" style="display: flex; justify-content: space-between; padding: 10px;">
            <h3>{{ post.username }}</h3>
            <h4>{{ post.date }}</h4>
        </div>
        <p>{{ post.body }}</p>
        <hr>
    {% endfor %}
</body>
</html>

Chapter_5/datas/templates/single_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    <div class="info" style="display: flex; justify-content: space-between; padding: 10px;">
        <h3>{{ post.username }}</h3>
        <h4>{{ post.date }}</h4>
    </div>
    <p>{{ post.body }}</p>
    <img src="{{ post.image.url }}" alt="{{ post.title }}" width="300px">
    <p><a href="{% url 'posts:list' %}">Back</a></p>
</body>
</html>

Chapter_5/templates/pages/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Posts</title>
</head>
<body>
    <h1>Welcome</h1>
    <h3><a href="{% url 'posts:list' %}">Posts</a></h3>
    <h3><a href="{% url 'users:register' %}">Resgister</a></h3>
</body>
</html>

Chapter_5/users/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register Page</h1>
</body>
</html>